#!/bin/sh

sudo apt-get update
sudo apt-get install -y devscripts python-pystache live-build pbuilder
sudo apt-get install -y live-build pbuilder git

if [ ! -d vyos-build ] ; then 
  git clone https://github.com/vyos/vyos-build.git
else
  echo "already cloned"
  cd vyod-build && git pull --rebase
fi
